# Lab 3-2-22
## Introduction to NUMPY

In [7]:
#Ex. 1
import numpy as np

# 1. Create a rank 1 array a by seeding values
a = np.array([7, 2, 9, 10])

# Print the type of a 
print('Type of a: ', type(a))

# Print the shape 
print('The shape of a is:', a.shape)

# Print each element
print('The elements are: ', a[0], a[1], a[2], a[3])
print('All elements are: ', a)


Type of a:  <class 'numpy.ndarray'>
The shape of a is: (4,)
The elements are:  7 2 9 10
All elements are:  [ 7  2  9 10]


In [5]:
# Change the 2 to an 8 in the array
a[1]=8

# Print the entire array
print(a)

#print the type of data in the a array
print('type of data inside the array is: ', a.dtype)
print(type(a[0]))

[ 7  8  9 10]
type of data inside the array is:  int32
<class 'numpy.int32'>


In [8]:
# 2. Create a rank 2 array b by seeding values
b = np.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])

print('shape: ', b.shape)
print('dtype: ', b.dtype)
print('all elements: \n', b)

shape:  (2, 3)
dtype:  float64
all elements: 
 [[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [9]:
print('Element in first corner: ', b[0,0])

Element in first corner:  5.2


In [10]:
print('Element in first corner: ', b[0][0])

Element in first corner:  5.2


In [13]:
#Ex. 2: Array creation

# 2.1. Create a length-10 integer array a filled with zeros and print it
#a=np.zeros(10, dtype=int)
a=np.zeros(10, dtype=float)
print('Array of zeros is: ', a)

Array of zeros is:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
a=np.zeros((2,2), dtype=float)
print('2D Array of zeros is: \n', a)

2D Array of zeros is: 
 [[0. 0.]
 [0. 0.]]


In [17]:
# 2.2. Create a 3x5 floating-point array b filled with 1s and print it
b=np.ones((3,5), dtype=float)
print('2D Array of ones is: \n', b)

2D Array of ones is: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
# 2.3. Create a 3x5 array c filled with 3.14 and print it
c=np.full((3,5), 3.14)
print('2D array of same number 3.14 is: \n', c)


2D array of same number 3.14 is: 
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [19]:
# 2.4. Generate an array from a list of 8 consecutive numbers
d=np.arange(1,9)
print('list of consecutive numbers: ', d)

list of consecutive numbers:  [1 2 3 4 5 6 7 8]


In [21]:
d1=np.arange(9)
print('list of consecutive numbers using arange(9): ', d1)

list of consecutive numbers using arange(9):  [0 1 2 3 4 5 6 7 8]


In [22]:
#Ex.3: Array attributes
#Check more info about the seed at https://www.w3schools.com/python/ref_random_seed.asp
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
 
print('x1 is: ', x1)
print('x2 is: \n', x2)
print('x3 is: \n', x3)

x1 is:  [5 0 3 3 7 9]
x2 is: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3 is: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [23]:
# print the dimension of array x3
print('x3 ndim: ', x3.ndim)

# print the shape of array x3
print('x3 shape: ', x3.shape)

# print the size of array x3 
print('x3 size: ', x3.size) 

# print the datatype of array x3
print('dtype: ', x3.dtype)

# print the itemsize of array x3
print('itemsize: ', x3.itemsize)

# print the number of bytes of array x3
print('nbytes:', x3.nbytes)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int32
itemsize:  4
nbytes: 240


In [24]:
#Add code to check if it is true that nbytes is equal to itemsize times size and print true or false depending on the result
if x3.nbytes == x3.itemsize*x3.size:
    print('True')
else:
    print('False')

True


In [25]:
#More compact way
print(x3.nbytes == x3.itemsize*x3.size)

True


In [26]:
#Write code to print the 1st element of x1, the last element of x1, and to change the second element to 8
print('x1 is: ', x1)
print('first element of x1 is: ', x1[0])
print('last element of x1 is: ', x1[-1])
x1[1] = 8

print('x1 is now: ', x1)

x1 is:  [5 0 3 3 7 9]
first element of x1 is:  5
last element of x1 is:  9
x1 is now:  [5 8 3 3 7 9]
