# Lab 3-9-2022
## Numpy Operations

In [1]:
import numpy as np
#Comparing np.add.reduce to np.sum
y = np.arange(1, 8)
adred = np.add.reduce(y)
print("y is: \n", y)
print("result using np.add.reduce is: ", adred)
s = np.sum(y)
print("result using np.sum is: ", s)

y is: 
 [1 2 3 4 5 6 7]
result using np.add.reduce is:  28
result using np.sum is:  28


In [2]:
#Outer method
#the outer method computes the product of all pairs of diff elements
x = np.arange(1, 6)
xx = np.multiply.outer(x, x)
print("x is: \n", x)
print("result using outer method: \n", xx)

x is: 
 [1 2 3 4 5]
result using outer method: 
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [4]:
#Numpy Matrix Multiplication
#Source: https://www.educative.io/blog/numpy-matrix-multiplication
#Case 1: With .dot (also called scalar multiplication)
X = [6, 7] 
    
Y = [[1, 3],
      [5, 7]]
print('This is np.dot(X,Y): \n', np.dot(X,Y))
print("----------")
print('This is np.dot(Y,X): \n', np.dot(Y,X))

#Note that the order matters
#Restriction: we can only multiply two matrices if the number of columns in the first matrix 
#is equal to the number of rows in the second matrix.
#np.dot is not recommended for high dimensional arrays

This is np.dot(X,Y): 
 [41 67]
----------
This is np.dot(Y,X): 
 [27 79]


In [5]:
#Case 2: With .matmul() 
X = [[6, 7],
      [8, 9]]     
Y = [[1, 3],
      [5, 7]]
MM=np.matmul(X,Y)
print('This is np.matmul(X,Y): \n', MM)

This is np.matmul(X,Y): 
 [[41 67]
 [53 87]]


In [6]:
#Case3: Element-wise matrix multiplication with .multiply()

#The sizes of the rows, columns, or submatrices that we pass as our operands should be the same. 
M1 = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])
M2 = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
print('This is np.multiply(M1,M2):\n', np.multiply(M1,M2))

This is np.multiply(M1,M2):
 [[ 1  6 15 28 45]
 [10 16 18 16 10]]


In [7]:
#Efficiency of Numpy Operations
#Comparing symbol (+) with uFunc (add)
#importing the modules
import numpy as np
import timeit

x = np.arange(1, 1000) #Generate an array from 1 to 999
print('Time taken by add method: ', end="")
%timeit np.add(2,x)

print('Time taken by arithmetic symbol: ', end="")
%timeit 2+x

Time taken by add method: The slowest run took 5.43 times longer than the fastest. This could mean that an intermediate result is being cached.
10.9 µs ± 6.42 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time taken by arithmetic symbol: The slowest run took 4.98 times longer than the fastest. This could mean that an intermediate result is being cached.
7.08 µs ± 4.97 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
#Efficiency of numpy vectorized operations
#Source: https://www.geeksforgeeks.org/vectorized-operations
#importing the modules
import numpy as np
import timeit

#vectorized sum
print('result  of np.sum on arange of 15000: ', np.sum(np.arange(15000)))
print("Time taken by vectorized sum: ", end ="")
%timeit np.sum(np.arange(15000))

print('------------')
#iterative sum
total=0
for item in range(0, 15000):
    total +=item
a=total

print("result computed by for loop: ", a)

print("Time taken by iterative sum: ", end="")
%timeit a

result  of np.sum on arange of 15000:  112492500
Time taken by vectorized sum: 73.3 µs ± 16.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
------------
result computed by for loop:  112492500
Time taken by iterative sum: 105 ns ± 20.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [12]:
#Stat aggregation examples
x3 =  np.random.randint(1000, size=(3,4,5)) #Three dimensional array
print("The three dimensional array is printed below in three parts: \n")
print(x3)

The three dimensional array is printed below in three parts: 

[[[ 88 293 266 646 650]
  [862 773 613 349 121]
  [733  78  18 210 186]
  [549 341 539 658 763]]

 [[332  28 225 571 510]
  [887 431 178 650 303]
  [534 714   9 784 218]
  [967 704 221 149 553]]

 [[315 698 694 656  16]
  [935 571 316 315 135]
  [129 180 525 716  97]
  [964 150 621 863 620]]]


In [13]:
print('Min is: ', np.min(x3))
print('Max is: ', np.max(x3))

Min is:  9
Max is:  967


In [15]:
print('Average is: ', np.average(x3))

Average is:  453.6666666666667


In [16]:
print('Average is: ', np.mean(x3))

Average is:  453.6666666666667


In [17]:
#Broadcasting examples 

#Adding a 2D array and 1D array
M = np.ones((2, 3))
a = np.arange(3)
print('M = \n', M)
print('a = ', a)
print('M+a = ', M+a)

M = 
 [[1. 1. 1.]
 [1. 1. 1.]]
a =  [0 1 2]
M+a =  [[1. 2. 3.]
 [1. 2. 3.]]


In [19]:
#Case where both arrays need to broadcast
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a + b
print('a = \n', a)
print('b = ', b)
print('a+b = \n', a+b)

a = 
 [[0]
 [1]
 [2]]
b =  [0 1 2]
a+b = 
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [20]:
#Case where two arrays are not compatible and gives an error
M = np.ones((3, 2))
a = np.arange(3)
print('M = \n', M)
print('a = ', a)
print('M+a = ', M+a)

M = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
a =  [0 1 2]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 